name: CI Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 21.x, 22.x, 23.x]
        mongodb-version: ['6.0', '7.0', '8.0']

    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Use Node.js $
      uses: actions/setup-node@v4
      with:
        node-version: $
        cache: 'npm'

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.12.0
      with:
        mongodb-version: $

    - name: Install dependencies 
      run: npm ci
    
    - name: Running tests
      run: npm test